// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqPElQrLhLUJGpyo5601nmFYFSJJiPKY',
    appId: '1:751486513331:web:2d4353e6cd4ac0551340c6',
    messagingSenderId: '751486513331',
    projectId: 'devera-news-221fa',
    authDomain: 'devera-news-221fa.firebaseapp.com',
    storageBucket: 'devera-news-221fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FVwSJa1PGkyURxKuHoI2Xu1-E-Z1Bks',
    appId: '1:751486513331:android:9ecf3460e6298b4a1340c6',
    messagingSenderId: '751486513331',
    projectId: 'devera-news-221fa',
    storageBucket: 'devera-news-221fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3WWFfdWZLP_ZA7r9AU8VY7AVdvoR89aM',
    appId: '1:751486513331:ios:0daed02617a91bc01340c6',
    messagingSenderId: '751486513331',
    projectId: 'devera-news-221fa',
    storageBucket: 'devera-news-221fa.appspot.com',
    iosClientId: '751486513331-45gva3opn14k8ks7ihp9m6g6l921ac77.apps.googleusercontent.com',
    iosBundleId: 'com.example.deveraNewsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3WWFfdWZLP_ZA7r9AU8VY7AVdvoR89aM',
    appId: '1:751486513331:ios:63dcd5300e0ceef11340c6',
    messagingSenderId: '751486513331',
    projectId: 'devera-news-221fa',
    storageBucket: 'devera-news-221fa.appspot.com',
    iosClientId: '751486513331-rkum1dn6eopv6bsi34p7np1k86f9euqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.deveraNewsApplication.RunnerTests',
  );
}
